name: Bug report
description: Signaler un problème dans MaisonConnect
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description du problème
      description: Explique clairement le bug rencontré.
      placeholder: Exemple= Le coffre-fort ne se verrouille pas correctement.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour reproduire
      description: Liste les étapes permettant de reproduire le bug.
      placeholder: |
        1. Lancer le projet
        2. Déverrouiller le coffre
        3. Constater l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Résultat attendu
      description: Explique ce qui devrait normalement se passer.
    validations:
      required: true